### ISSUE TITLE
 大神，server目录下config.js 这里面的代码我看不懂，请问这个AV是何功能？

### ISSUE THREAD

**Issue by huihongzhou** [hilongjw/vue-zhihu-daily#1]
const AV = require('leanengine')

const config = {
    appId: 'dpeFsmm4JIVgnmQP0tizLCcO-gzGzoHsz',
    appKey: '2ph8iVVCL1TtNjKNCUG8TtKn'
}

AV.initialize(config.appId, config.appKey)
AV.Cloud.useMasterKey()

exports.AV = AV
呜哇~

**Comment by hilongjw** [comment]
是引入leancloud的nodejs sdk，这个项目图片的存储是通过leancloud的file 服务存到七牛的。
https://github.com/hilongjw/vue-zhihu-daily/blob/master/server/routes/imagebox.js

**Comment by huihongzhou** [comment]
ok~wonderful
