### ISSUE TITLE
node的问题

### ISSUE THREAD

**Issue by TerrenceFong** [hilongjw/vue-zhihu-daily#16]
请问如果没有nodejs的基础的话，是不是暂时不推荐学习这个项目的？
还有这里的node应该只做了图片缓存的吧？
imagebox.js是您自己写出来的吗？太厉害了

**Comment by hilongjw** [comment]
是的，imagebox 是图片转存，是通过 node 转存到 CDN，是为了解决知乎的图片防盗链问题。
