### ISSUE TITLE
哈喽，我请问一下this.$http.get(this.$Api('http://news-at.zhihu.com/api/4/themes'))里面的this.$Api是什么意思？

### ISSUE THREAD

**Issue by xiaoosnggao** [hilongjw/vue-zhihu-daily#18]
![image](https://cloud.githubusercontent.com/assets/16183057/21796472/f0cba7c0-d743-11e6-8d8e-b785dfdcda9b.png)
我写了this.$api的话会报错

**Comment by hilongjw** [comment]
只是返回一个请求当前API的代理地址的函数
[/src/index.js](https://github.com/hilongjw/vue-zhihu-daily/blob/master/src/index.js)
```javascript 
Vue.prototype.$Api = (url) => {
    return window.location.origin + '/readapi?uri=' + url
}
```

**Comment by xiaoosnggao** [comment]
这样的话，在本地还是无法请求到数据对么？只有上传到知乎的域名下面才可以正常请求到数据是么？

**Comment by hilongjw** [comment]
这里是通过Nodejs 代理了知乎的数据接口，当然是能拿到数据的

`http://zhihu.bood.in/readapi?uri=http://news.at.zhihu.com/api/4/news/before/20170110`

**Comment by xiaoosnggao** [comment]
好的 谢谢您
