### ISSUE TITLE
手机端无法记录滚动位置

### ISSUE THREAD

**Issue by Someant** [hilongjw/vue-zhihu-daily#2]
我以前自己用vuejs的时候也碰到过这个问题，一直没解决，刚用手机测试下了下，也存在这个问题

**Comment by hilongjw** [comment]
这个可以在相应的主视图组件里实现的，在路由的hook的 activate里设置滚动位置， deactivate记录当前的位置，不过现在这项目里还没有做，我之后有时间会实现。
