### ISSUE TITLE
大神，localhost/admin,和dashboard登陆页面如何访问，

### ISSUE THREAD

**Issue by zhangbiggs** [hilongjw/vue-zhihu-daily#5]

**Comment by hilongjw** [comment]
这个是引用我另外一个工程的，我还没想好zhihu这个项目需不需要管理admin，多入口访问的话，你可以参考我的这个项目 https://github.com/hilongjw/AweSiteChat

**Comment by zhangbiggs** [comment]
多谢，想学习多一点vue项目构建的技巧，这里目录结构是我看见最适合的
