### ISSUE TITLE
nginx配置问题

### ISSUE THREAD

**Issue by lidelin** [hilongjw/vue-zhihu-daily#9]
请教一下部署在nginx应该配置呢？
我配了之后，会报这个错误：
app.js:23 GET http://ldl.vue.com/readapi?uri=http://news.at.zhihu.com/api/4/news/before/20160629 404 (Not Found)

谢谢～

**Comment by hilongjw** [comment]
这个项目不只是一个前端工程，是需要node后端的
建议看一下server目录下的文件

**Comment by lidelin** [comment]
我刚开始学习前端不久，对node做后端完全没接触过，server目录下的代码看得有点蒙...
请教一下我怎样去学习相关的知识呢？

**Comment by hilongjw** [comment]
express，leancloud，前者是一个nodejs应用框架，后面是一个不错的国内baas云服务

**Comment by lidelin** [comment]
好的，谢谢，我去学习一下

**Comment by hilongjw** [comment]
好的，不客气
